# -*- coding: utf-8 -*-
"""Customer_Churn_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FAczhGah0XtLljJkQTlpSYF3hue0CJvN
"""

#DAVID SANTIAGO PAEZ
#28/04/2026

"""# Customer Churn Prediction using Logistic Regression
DAVID SANTIAGO PAEZ

28/04/2026

Proyecto de Machine Learning para predecir abandono de clientes (Churn) en telecomunicaciones usando Regresión Logística.
"""

# -----------------------------------
# IMPORTACIÓN DE LIBRERÍAS
# -----------------------------------

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

# -----------------------------------
# CARGA DEL DATASET
# -----------------------------------

url = "https://raw.githubusercontent.com/IBM/telco-customer-churn-on-icp4d/master/data/Telco-Customer-Churn.csv"

df = pd.read_csv(url)

df.head()

# -----------------------------------
# INFORMACIÓN GENERAL
# -----------------------------------

print(df.shape)
df.info()
df.isnull().sum()

# -----------------------------------
# LIMPIEZA DE DATOS
# -----------------------------------

# Convertir TotalCharges a número
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

# Eliminar nulos
df = df.dropna()

print(df.shape)

# -----------------------------------
# EDA RÁPIDO
# -----------------------------------

df["Churn"].value_counts()

df["Churn"].value_counts().plot(kind="bar")
plt.title("Distribución de Churn")
plt.show()

# -----------------------------------
# ENCODING
# -----------------------------------

# Variable objetivo
y = df["Churn"].map({"Yes":1, "No":0})

# Variables predictoras
X = df.drop(["Churn", "customerID"], axis=1)

# Convertir texto a números
X = pd.get_dummies(X, drop_first=True)

print(X.shape)
X.head()

# -----------------------------------
# TRAIN / TEST SPLIT
# -----------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(X_train.shape, X_test.shape)

# -----------------------------------
# SCALING
# -----------------------------------

X_train = X_train.astype(float)
X_test = X_test.astype(float)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# -----------------------------------
# MODELO
# -----------------------------------

modelo = LogisticRegression(
    max_iter=5000,
    solver="liblinear"
)

modelo.fit(X_train_scaled, y_train)

# -----------------------------------
# MÉTRICAS
# -----------------------------------

y_pred = modelo.predict(X_test_scaled)

print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))

print(confusion_matrix(y_test, y_pred))

# -----------------------------------
# IMPORTANCIA DE VARIABLES
# -----------------------------------

coef = pd.DataFrame({
    "Variable": X.columns,
    "Coeficiente": modelo.coef_[0]
})

coef.sort_values(by="Coeficiente", ascending=False).head(10)

top = coef.sort_values(by="Coeficiente", ascending=False).head(10)

plt.figure(figsize=(10,6))
plt.barh(top["Variable"], top["Coeficiente"])
plt.gca().invert_yaxis()
plt.title("Variables que aumentan Churn")
plt.show()

"""# Conclusiones

- El modelo logró ~80% accuracy.
- Contratos largos reducen churn.
- Clientes nuevos presentan mayor riesgo.
- Fiber optic mostró alta relación con churn.
- Logistic Regression ofrece interpretabilidad y buen baseline.
"""