# -*- coding: utf-8 -*-
"""Housing_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-yaQConPJXKlNVFJcleYLW1UGB7A4iYE
"""

# DAVID SANTIAGO PAEZ
# 28/04/2026

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

from sklearn.datasets import fetch_california_housing  #Se importa el dataset

data = fetch_california_housing()

df = pd.DataFrame(data.data, columns=data.feature_names)
df['PRICE'] = data.target

print(df.head())

df.sample(5)

df.describe()

df.corr()

axes = pd.plotting.scatter_matrix(df, alpha=0.2)

for ax in axes.flatten():
    ax.xaxis.label.set_rotation(90) #gira el texto del eje X
    ax.yaxis.label.set_rotation(0)  #deja el eje Y horizontal
    ax.yaxis.label.set_ha('right')  #alinea el texto a la derecha

plt.tight_layout() #organiza automáticamente los espacios, evita que se sobrepongan
plt.gcf().subplots_adjust(wspace=0, hspace=0) # elimina espacios entre gráficos, wspace → espacio horizontal, hspace → espacio vertical
plt.show()

df = df.drop(['AveBedrms','Population','AveOccup','Longitude'], axis=1)

df.head(5)

X = df[['MedInc', 'AveRooms', 'HouseAge', 'Latitude']].to_numpy()
y = df[['PRICE']].to_numpy()

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

print("Coeficientes:", model.coef_)
print("Intercepto:", model.intercept_)

y_pred = model.predict(X_test)

print("MAE:", mean_absolute_error(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2:", r2_score(y_test, y_pred))

# -----------------------------------
# REGRESION POLINOMIAL GRADO 2
# -----------------------------------

from sklearn.preprocessing import PolynomialFeatures

poly_2 = PolynomialFeatures(degree=2)  #creamos variables polinomiales de grado 2
X_poly_2 = poly.fit_transform(X_scaled)

X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(X_poly_2, y, test_size=0.2, random_state=42) # volvemos a Train/Test pero ahora con x_poly

model_2 = LinearRegression() #Entrenamos el modelo
model_2.fit(X_train, y_train)

y_pred2 = model_2.predict(X_test)

print("R2", r2_score(y_test, y_pred))
print("RMSE", np.sqrt(mean_squared_error(y_test, y_pred)))
print("MAE", mean_absolute_error(y_test, y_pred))
print("MSE", mean_squared_error(y_test, y_pred))

# -----------------------------------
# REGRESION POLINOMIAL GRADO 3
# -----------------------------------

poly_3 = PolynomialFeatures(degree=3)
X_poly_3 = poly_3.fit_transform(X_scaled)

X_train_3, X_test_3, y_train_3, y_test_3 = train_test_split(X_poly_3, y, test_size=0.2, random_state=42) # volvemos a Train/Test pero ahora con x_poly3

model_3 = LinearRegression() #Entrenamos el modelo
model_3.fit(X_train_3, y_train_3)

y_pred_3 = model_3.predict(X_test_3)

print("R2", r2_score(y_test_3, y_pred_3))
print("RMSE", np.sqrt(mean_squared_error(y_test_3, y_pred_3)))

modelos = ['Linear', 'Poly G2', 'Poly G3']
r2_scores = [0.5043, 0.5188, 0.5139]
rmse_scores = [0.8059, 0.7940, 0.7980]

plt.figure(figsize=(10,5))
plt.bar(modelos, r2_scores)
plt.title("Comparación R²")
plt.ylabel("R² Score")
plt.show()

plt.figure(figsize=(10,5))
plt.bar(modelos, rmse_scores)
plt.title("Comparación RMSE")
plt.ylabel("RMSE")
plt.show()

results = pd.DataFrame({
    'Modelo': ['Linear Regression', 'Polynomial G2', 'Polynomial G3'],
    'R2': [0.5043, 0.5188, 0.5139],
    'RMSE': [0.8059, 0.7940, 0.7980]
})

results

