# -*- coding: utf-8 -*-
"""Salario_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ADo_F69O89Usn5NQSYCZkd1Z4rBxlC36
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split   # Para dividir datos en entrenamiento y prueba
from sklearn.linear_model import LinearRegression      # Modelo de regresión lineal

#creacion de dataset manual

# Años de experiencia(X)
años = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
# Salario correspondiente (y)
salario = np.array([1000,1200,1400,1600,1800,2000,2200,2400,2600,2800,3000,3200])

X_train, X_test, y_train, y_test = train_test_split(años, salario, test_size=0.2, random_state=42)

modelo = LinearRegression()

modelo.fit(X_train.reshape(-1, 1), y_train)  # Convierte lista en formato correcto para ML
                                             # -1 = calcula filas automáticamente
                                             # 1 = una sola característica

prediccion = modelo.predict([[7]])

print("Salario para 7 años: ", prediccion)

plt.scatter(años, salario)
plt.plot(años, modelo.coef_*años + modelo.intercept_, color='blue')
plt.xlabel("Años de experiencia")
plt.ylabel("Salario")
plt.title("Regresión Lineal - Salario")
plt.show()